# Assetic Configuration
assetic:
    debug:  "%kernel.debug%"
    use_controller:
      enabled:  "%kernel.debug%"
      profiler: false
    bundles:
      - NoveoBundle
    filters:
      uglifycss:
        bin: "/usr/local/bin/uglifycss"
      uglifyjs:
        bin: "/usr/local/bin/uglifyjs"
    workers:
      # see https://github.com/symfony/AsseticBundle/pull/119
      # Cache can also be busted via the framework.assets.version
      # setting - see the "framework" configuration section
      cache_busting:
        enabled:  true
    assets:
      styles:
        inputs:
          - "assets/css/styles.css"
        output: "assets/css/styles_uglified.css"
        filters:
          - ?uglifycss
      scripts:
        inputs:
          - 'assets/js/scripts.js'
        output: "assets/js/scripts_uglified.js"
        filters:
          - ?uglifyjs