routing:
    paths:
        index:
            path: /
            defaults: { controller: 'Module1:Controller1:action1' }
            methods:  [GET]
        index1:
            path: /name
            defaults: { controller: 'Module1:Controller1:action1' }
            methods:  [GET]
        index2:
            path: /name/{id}
            defaults: { controller: 'Module1:Controller1:action1' }
            methods:  [GET]
        index3:
            path: /name/{id}/name1
            defaults: { controller: 'Module1:Controller1:action1' }
            methods:  [GET]
        index3:
            path: /name/locale/{name}
            defaults: { controller: 'Module1:Controller1:action1' }
            methods:  [GET]
            parameters:
                name:
                    value: html|rss
                    type: choice
        get_user_by_username:
            path: /2.0/users/{username}/articles/{_locale}/{year}/{title}
            defaults: {
                controller: 'Module2:Controller2:action2',
                _locale: en
                }
            parameters:
                _locale:
                    value: en|fr
                    type: choice
                _format:
                    value: html|rss
                    type: choice
                year:
                    value: \d+
                    type: regexp
            methods:  [GET]