# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  noveo.service.user_service:
    class: NoveoBundle\Service\UserService
    arguments: ['@service_container']
  noveo.service.group_service:
    class: NoveoBundle\Service\GroupService
    arguments: ['@service_container']
  noveo.service.event_service:
    class: NoveoBundle\Service\EventService
    arguments: ['@service_container']
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: setNotFoundPage  }
