version: '2'
services:
  proxy:
    restart: always
    image: nginx:1.11
    network_mode: host
    volumes:
      - "./config/conf.d:/etc/nginx/conf.d"
      - "./config/nginx.conf:/etc/nginx/nginx.conf"

