version: '2'
services:
  db:
    restart: always
    image: mysql:5.6
    network_mode: host    
    volumes:
      - "./data:/var/lib/mysql"
      - "./config:/etc/mysql/conf.d"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
